### ISSUE TITLE
Coleccion de Postman

### ISSUE THREAD

**Issue by Jackman97** [gti-sos/SOS2021-23#13]
Tener una colección de POSTMAN con nombre SOS2021-XX-YYYYY  (siendo YYYYYY el nombre del recurso ofrecido tal como aparece en la columna “datos” de la primera hoja de la ficha de la propuesta de trabajo)  que tenga una petición GET a la página de información (/info/YYYYYY) desplegada en heroku.

**Comment by Beelthazad** [comment]
![image](https://user-images.githubusercontent.com/22844696/111885378-b1d5ad00-89c7-11eb-9fc6-b056c92cbbf1.png)
